SET @db_name = '';

DELIMITER $$
CREATE PROCEDURE IF NOT EXISTS localhostize(IN db_name VARCHAR(255))
BEGIN

DECLARE finished INTEGER DEFAULT 0;
DECLARE t_name VARCHAR(255);
DECLARE update_query VARCHAR(225);


DECLARE cur_tables CURSOR FOR SELECT TABLE_NAME FROM information_schema.tables WHERE TABLE_SCHEMA = db_name AND TABLE_NAME LIKE '%options';
	
DECLARE CONTINUE HANDLER FOR NOT FOUND SET finished = 1;


END $$
DELIMITER ;


CALL localhostize(@db_name);

DROP PROCEDURE IF EXISTS localhostize;

